title: Gyan Prakash Rai
description: >
  AWS & Azure Platform Engineer • DevOps Engineer • Cloud Infrastructure Specialist

theme: jekyll-theme-primer

show_downloads: false

github:
  is_project_page: true

markdown: kramdown

kramdown:
  input: GFM

timezone: Asia/Singapore