title: Gyan Prakash Rai
description: >
  Cloud Infrastructure • Kubernetes • Terraform • DevOps Automation • Platform Engineering

remote_theme: jekyll-theme-cayman

show_downloads: false

github:
  is_project_page: true

markdown: kramdown

kramdown:
  input: GFM

timezone: Asia/Singapore